### ISSUE TITLE
Usable for production?

### ISSUE THREAD

**Issue by GildedHonour** [heartsucker/rust-csrf#14]
Is it ready for production?

How to use it, are the examples?

**Comment by heartsucker** [comment]
Hey @GildedHonour. You can checkout out the crate `iron-csrf` for an example of using it with `iron`. I also have a project that shows a simple `iron` webapp that uses `iron-csrf` here: https://github.com/heartsucker/iron-reference.

I'd say that yes, this is usable for production. What rust framework were you planning on using? I could toss together something for one of the non-`iron` frameworks pretty quick if you you needed it (maybe?).

**Comment by asmarton** [comment]
@heartsucker I'm interested in using this along with [Rocket](https://rocket.rs/). Would it be enough to let Rocket manage a `AesGcmCsrfProtection` struct and grab it using a `State<AesGcmCsrfProtection>` request guard whenever I write a handler for a page that needs tokens?

**Comment by heartsucker** [comment]
I have never used rocket, so unfortunately I can't say. Maybe?

**Comment by heartsucker** [comment]
Closing this ticket as it is a question and not a feature request or bug report.
